dist: trusty
sudo: false
addons:
  chrome: stable
language: node_js
node_js:
- "node"
before_install:
- export CHROME_BIN=/usr/bin/google-chrome-stable
before_script:
- npm run lint
after_success:
- cat karma-out.log
after_failure:
- cat karma-out.log
